#   HPack docs[1] don't describe options described in Cabal docs[2].
#   Also see Stack docs[3] for package.yaml vs. stack.yaml usage.
#   [1]: https://github.com/sol/hpack
#   [2]: https://cabal.readthedocs.io/en/3.6/cabal-package.html
#   [3]: https://docs.haskellstack.org/en/stable/topics/stack_yaml_vs_cabal_package_file/

spec-version:       0.36.0

name:               kmonad
version:            0.1.0.0
github:             nishantjr/kmonad
license:            AllRightsReserved
author:
  - "Nishant Rodrigues <nishantjr@gmail.com>"
  - "Curt J. Sampson <cjs@cynic.net>"
copyright:  2025 Nishant Rodrigues and Curt Sampson
category:   Programming Languages
synopsis:   A proof-of-concept reimplementation of K as a Haskell library.
description: See the README for more details.

extra-source-files:
  - README.md

####################################################################
#   Haskell and GHC configuration; library dependencies.
#   For further info and references, see doc/haskell.md.

default-extensions:         # Enabled in every module.
  - NumericUnderscores
  - BangPatterns
  - StandaloneDeriving

#   This is essentialy just documentation of what LANGUAGE pragmas we use.
other-extensions: []

ghc-options:
  - -rtsopts                # Allows +RTS … -RTS when running compiled progs.
                            #   https://downloads.haskell.org/ghc/latest/docs/users_guide/runtime_control.html
  - -Wall                   # Not actually *all* warnings, thus additions below.
  - -Wno-name-shadowing     # Having to avoid collisions w/top-level names
                            #    is more awkward than helpful.
  - -Wcompat                # Helps with future compatibility.
  - -Widentities            # Prelude numeric conversions (`toInteger` etc.) to same type.
  - -Wmissing-export-lists  # Ought to be in `all`, we think.
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

dependencies:
  - base >= 4.7 && < 5
  - containers
  - liquidhaskell
  - liquid-prelude

####################################################################
#   Libraries, executables, tests.

library:
  source-dirs: [src, src/experiment]

executables:
  hello:
    source-dirs:        app
    main:               Hello.hs
    other-modules:      []
  benchmark:
    source-dirs:        app
    main:               Benchmark.hs
    other-modules:      []
    dependencies:       [ kmonad ]
  optimization:
    source-dirs:        app
    main:               Optimization.hs
    other-modules:      []
    dependencies:       [ kmonad ]

tests:
  kmonad-test:
    source-dirs:         unit-test
    main:                Spec.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:       [ kmonad ]
