#!/usr/bin/env bash
set -Eeuo pipefail

trap 'ec=$?; echo 1>&2 "INTERNAL ERROR: ec=$ec line=$LINENO cmd=$BASH_COMMAND";
      exit $ec;' ERR

elapsed_start=$(date +%s%2N)   # 10s of milliseconds since the epoch
elapsed() {                    # fractional seconds (2 places) since start
    local msx10=$(( $(date +%s%2N) - $elapsed_start ))
    echo "$(($msx10/100)).$(($msx10%100))"
}

die()  { ec="$1"; shift; echo 1>&2 "ERROR ($ec):" "$@"; exit $ec; }
fail() {
    ec=$?
    [[ -n $@ ]] && echo 1>&2 "$@"
    echo 1>&2 "FAILED exitcode=$ec ($(elapsed)s)"
    exit $ec
}
warn()  { echo 1>&2 'Warning:' "$@"; }

since_timestamp() {
    local tsdir="$BUILDDIR/timestamp"
    local stampfile="$1"; shift
    local seconds="$1"; shift
    [ "${seconds}" -gt 0 ]  # bad arg generates internal error
    mkdir -p "$tsdir"
    local last_time=$(stat -c %Y "$tsdir/$stampfile" 2>/dev/null || true)
    [[ $(($last_time + $seconds)) -gt $(date +%s) ]] && return
    touch "$tsdir/$stampfile"
    echo "$@"
    "$@"
}

####################################################################

clean() {
    local cleantrees=(
        #   We don't clean .build/ghc-core/*.core on a "small" clean
        #   because this doesn't affect future builds at all, and
        #   regenerating them can be a pain.
        "$BUILDDIR"/ghc-core/obj/
        "$BUILDDIR"/timestamps/
        #   We keep this here instead of putting it under .build/ because
        #   we expect stand-alone `stack` invocations which will look for
        #   it only here.
        "$PROJDIR"/.stack-work/
        #   Though generated files in the repo, distributions of specific
        #   versions of the source would probably include these at these
        #   exact locations. See .gitignore for more details.
        "$PROJDIR"/stack.yaml.lock      # See .gitignore for details
        "$PROJDIR"/*.cabal              #   on these two items.
        #   It's not clear how to move this to a build directory.
        "$PROJDIR/src/.liquid/"
    )
    rm -rf "${cleantrees[@]}"
}

####################################################################

#   • We automatically install stack for users that don't have it on the
#     principle that you very rarely want a different installation (e.g., a
#     distro-packaged version), and even there it would get quite hairy
#     because of us wanting particular Haskell versions.
#   • This may need sudo access to install required system packages;
#     there's no way around this.
#   • This forces the install of the `stack` binary to ~/.local/bin/
#     because we don't want to be inadvertantly affecting the version of
#     stack that others on the system might be using. (If someone doesn't
#     have that in their path; the installer will warn about this.)
install_stack() {
    stack --version >/dev/null 2>&1 || {
        echo '───── Installing Haskell Stack'
        curl -sSL https://get.haskellstack.org/ \
            | bash -s -- --quiet --dest $HOME/.local/bin/ \
            || fail
    }
}

#   XXX HPack is a serious pain to bootstrap via cabal and Hackage, and
#   it's just a stand-alone utility anyway, so we simply grab the latest
#   release binary from GitHub. Unfortunately, that has only a Linux
#   (presumably x86_64) binary, so this does at some point need to be
#   properly bootstrapped so it can work on Mac, etc.
#
#   HPack does provide a get-hpack.sh script[1], but it's not only
#   hard-coded to install to ~/.local/bin/, but also has an..."interestig"
#   way of determining OS version: `os="${1:-${TRAVIS_OS_NAME:-linux}}"`.
#   So we just do our own download for the moment.
#
#   [1]: https://raw.githubusercontent.com/sol/hpack/main/get-hpack.sh
#
install_hpack() {
    [[ -x $TOOLBIN/hpack ]] && return 0

    platform='Linux x86_64'
    echo "───── Installing HPack for $platform"
    [[ $platform = $(uname -sm) ]] || die 9 \
        "install_hpack() supports only $platform, not $(uname -sm)"
    #   XXX We don't even bother to look up the latest version; we just
    #   download a fixed one, and update by hand when necessary.
    url='https://github.com/sol/hpack/releases/download/0.38.2/hpack_linux.gz'
    curl -sSL "$url" | gunzip > "$TOOLBIN/hpack"
    chmod +x "$TOOLBIN/hpack"
}

#   This sets $cabal to the `cabal` executable we will use for builds.
#   We assume that if there's a `cabal` available in $PATH, regardless
#   of version, that's the one we should use because that's what the
#   developer will be using at the command line. (We warn if the version
#   is lower than we would like.) Otherwise we examine what's available
#   in ~/.ghcup/bin/ and take either the default version set there, or
#   the highest version available.
find_cabal() {
    declare -g cabal
    local  minver=3.11      # Warn if cabal we use is less than this version.
    #   The `find` below doesn't do a proper numeric sort, but it produces
    #   a good-enough result that it's not worth splitting on '-' and again
    #   on '.' to try to get the very latest minor release.
    local ghcup_bin="$HOME/.ghcup/bin"
    local exe
    for exe in                      \
        cabal                       \
        "$ghcup_bin/cabal"          \
        $([[ -d $ghcup_bin ]]       \
            && find "$ghcup_bin" -name cabal-\* \
            | sort -r) \
    ; do
        "$exe" --numeric-version >/dev/null 2>&1 || continue
        local ver=$("$exe" --numeric-version)
        [[ $ver < $minver ]] && warn "version $ver < $minver for $exe"
        cabal="$exe"
        return 0
    done
    die 3 'Cannot find a `cabal` executable. Install one with ghcup?'
}

#   Unlike Cabal, where pretty much any version will work, only specific
#   versions of GHC can work with Liquid Haskell. Unless the user has
#   specified an override, we attempt to chose the earliest from our
#   list of preferred versions.
find_ghc() {
    grep -qs '^with-compiler:' "$PROJDIR/cabal.project.local" && return 0

    local prefvers=(9.10.2  9.10.1  9.8.2)  # XXX add 9.12.2
    local ghcup_bin="$HOME/.ghcup/bin"
    #   XXX exit if we already have a preferred version in
    #   cabal.project.local.
    local ver
    for ver in "${prefvers[@]}"; do
        local ghcpath="$ghcup_bin/ghc-$ver"
        "$ghcpath" --numeric-version >/dev/null 2>&1 || continue
        $cabal configure --enable-append --disable-backup \
            --with-compiler "$ghcpath"
        return 0
    done
    die 3 'Cannot find a GHC version. Install one with ghcup or use the -G option.'
}

#   Liquid Haskell needs an SMT solver; we use Z3 as suggested, in part
#   because it's widely available in many Linux distros. But there are
#   issues with different versions being not quite right; we may want
#   just to build this ourselves.
install_z3() {
    z3 --version >/dev/null 2>&1 || {
    echo '───── Installing Z3'
    sudo apt install z3 \
        || die 3 'Cannot `apt install z3`; try your own package manager?'
    }
}

#   Some development tools available from Stackage are a binary we run,
#   rather than a library we use, and we appear to be unable to add those
#   sorts of things to our {package,stack}.yaml. This adds these to the
#   current project to make them available via `stack exec`. (They are
#   actually available globally for any Stack-using project using the same
#   resolver and, where compiler-specific, compiler version.)
install_ghc_core() {
    pcre-config --version >/dev/null 2>&1 || {
        echo '───── Installing libpcre3-dev'
        #   XXX Seems this wants to produce two dozen or more lines of output
        #   no matter what we do to try to make it quiet.
        sudo apt -q -q -qq install -y -q -q -qq libpcre3-dev \
            || die 3 'Cannot `apt install libpcre3-dev`; try your own package manager?'
    }
    #   Ensure deps are installed at this point or Stack will install GHC
    #   etc. here, with no output, producing a long, mysterious wait.
    stack exec -- ghc-core -h >/dev/null 2>&1 || stack build ghc-core
}

####################################################################

generate_ghc_core() { (
    command cd "$PROJDIR"
    commit=$(git describe --always --dirty)
    mkdir -p .build/ghc-core/obj/
    for src in app/*.hs src/*.hs; do
        #   ghc will generate an executable if the name of the module
        #   is `Main` and places it in the source dir no matter the
        #   -outputdir setting, so we have to disable that manually.
        #   But we _cannot_ use -o on non-Main files here for some
        #   reason.
        oarg=; [[ $src = app/* ]] && oarg='-o /dev/null'

        #   -O2 is the default; we use -O1 because that's the much more
        #   typical optimisation level for production code and compiles
        #   faster for very little worse execution time and space.
        stack exec -- ghc-core --no-syntax --no-cast --no-asm \
            -- -O1 $oarg -outputdir .build/ghc-core/obj/ \
            "$src" > ".build/ghc-core/$(basename "$src" .hs)-$commit.core" \
            || fail "ghc-core: cannot compile $src"
    done
) }

####################################################################
#   Argument Parsing

export PROJDIR=$(cd "$(dirname "$0")" && pwd -P)
export BUILDDIR="$PROJDIR/.build"
export TOOLBIN="$BUILDDIR/tool/bin"; mkdir -p "$TOOLBIN"; PATH="$TOOLBIN:$PATH"

verbosity=0         # Cabal verbosity level (default 1 but we always override
                    # it) and perhaps other things.
ghc_requested=      # Non-empty = user has requested use of a specific GHC.
lhver=              # Switch to different version of Liquid Haskell.
ghci_modules=()     # Run ghci after build, :load! the given modules, and
ghci_exprs=()       #   then evaluate the given expressions.
gen_ghc_core=false  # Generate .build/ghc-core/ files for all source files.
while [[ ${#@} -gt 0 ]]; do case "$1" in
    --)             shift; break;;
    -C|-c)          shift; clean;;
    -G)             shift; ghc_requested="$1"; shift;;
    -g)             shift; gen_ghc_core=true;;
    -v|--verbose)   shift; verbosity=$(($verbosity+1));;    # multiple times ok
    -l|--lhver)     shift; lhver="$1"; shift;;
    -m|--module)    shift; ghci_modules+=("$1"); shift;;
    -e|--expr)      shift; ghci_exprs+=("$1"); shift;;
    -*)             die 2 "Unknown option: $1";;
    *)              break;;
esac; done

####################################################################
# Main

[[ -n $lhver ]] && (
    command cd "$PROJDIR"
        for file in stack.yaml; do
            vfile=lhver/$lhver-$file
            if [[ -r lhver/$lhver-$file ]]; then
                rm -f $file
                ln -s $vfile $file
                echo "$file → $(readlink $file)"
            else
                echo "Warning: $vfile not found; leaving existing file"
            fi
        done
)

echo '━━━━━ Development Tools'
install_z3
install_hpack
(cd "$PROJDIR" && hpack --silent)
find_cabal   # sets global $cabal
if [[ -z $ghc_requested ]]; then
    find_ghc
else
    echo -n 'Setting requested GHC: '
    "$ghc_requested" --numeric-version \
        || die 2 "Reqested GHC failed: $ghc_requested"
    $cabal configure --enable-append --disable-backup \
        --with-compiler "$ghc_requested"
fi
install_stack
#   Ensure toolchain is installed before checking for ghc core, because
#   otherwise the ghc core check will silently install GHC etc., giving
#   a long, mysterious wait.
stack build --dependencies-only --test --bench
install_ghc_core

echo '━━━━━ Build'
cd "$PROJDIR"
#   We want to regularly build with the latest versions of our dependencies
#   so we can quickly see any problems they introduce. This can slow things
#   down a bit, so just do this daily.
since_timestamp stack.yaml.lock 86400 rm -f stack.yaml.lock
stack build --cabal-verbosity=$verbosity || fail

[[ -n ${ghci_exprs[*]} ]] && {
    ghci_inputs=(':set prompt "▪ "')
    [[ -n ${ghci_modules[*]} ]] && ghci_inputs+=(":load! ${ghci_modules[*]}")
    ghci_inputs+=("Prelude.putStrLn $ Prelude.replicate 79 '─'")
    ghci_inputs+=("${ghci_exprs[@]}")
    printf '%s\n' "${ghci_inputs[@]}" | stack ghci --no-load || fail
}

#   Automatically generate core output for later examination
#   and comparison between commits.
$gen_ghc_core && generate_ghc_core

stack test || fail "Tests failed."

echo "OK ($(elapsed)s)"
