#!/usr/bin/env bash
set -Eeuo pipefail

trap 'ec=$?; echo 1>&2 "INTERNAL ERROR: ec=$ec line=$LINENO cmd=$BASH_COMMAND";
      exit $ec;' ERR

die()  { ec="$1"; shift; echo 1>&2 "ERROR ($ec):" "$@"; exit $ec; }
fail() { ec=$?; echo "FAILED exitcode=$ec ($(elapsed)s)"; exit $ec; }

elapsed_start=$(date +%s)
elapsed() { echo $(( $(date +%s) - $elapsed_start )); }

####################################################################

export PROJDIR=$(cd "$(dirname "$0")" && pwd -P)

#   • We automatically install stack for users that don't have it on the
#     principle that you very rarely want a different installation (e.g., a
#     distro-packaged version), and even there it would get quite hairy
#     because of us wanting particular Haskell versions.
#   • This may need sudo access to install required system packages;
#     there's no way around this.
#   • This forces the install of the `stack` binary to ~/.local/bin/
#     because we don't want to be inadvertantly affecting the version of
#     stack that others on the system might be using. (If someone doesn't
#     have that in their path; the installer will warn about this.)
stack --version >/dev/null 2>&1 || {
    echo '━━━━━ Installing Haskell Stack'
    curl -sSL https://get.haskellstack.org/ \
        | bash -s -- --quiet --dest $HOME/.local/bin/ \
        || fail
}

echo '━━━━━ Build'
cd "$PROJDIR"
#   We want to regularly build with the latest versions of our dependencies
#   so we can quickly see any problems they introduce. If rebuilding the
#   lock file every time becomes too slow, it's fine to remove it just once
#   per day or whatever.
rm -f stack.yaml.lock
stack build || fail

echo "OK ($(elapsed)s)"
