#!/usr/bin/env bash
#
#   Benchmark build and interpretation of sum.imp.
#
#   You may skip the (long) compile stage with the `--skip-kompile` option;
#   it's the developer's responsibility to ensure that they doesn't do this
#   when the semantics need to be (re-)compiled.
#
set -Eeuo pipefail
trap 'ec=$?; echo 1>&2 "INTERNAL ERROR: ec=$ec line=$LINENO cmd=$BASH_COMMAND";
      exit $ec;' ERR

die() { ec=$1; shift; echo "$@"; exit $ec; }

time_run() {
    type -P time >/dev/null \
        || die 3 '`time` command not found. Install `time` package?'
    command time -f "\
elapsed/user/system:\t%es\t%Us\t%Ss
    average/max mem:\t%K KB\t%M KB" \
   "$@"
}

####################################################################

benchmark_h() {
    echo "───── build/test"
    $skip_compile \
        && { echo "WARNING: build/test skipped"; } \
        || ./Test
    echo "───── run"
    time_run $(stack path --local-install-root)/bin/benchmark +RTS -sstderr
}

benchmark_k() {
    mkdir -p "$BUILDDIR"
    echo "───── kompile"
    $skip_compile \
        && { echo "WARNING: kompile skipped"; } \
        || time_run kompile -o "$BUILDDIR" bench/imp.k
    echo "───── krun"
    #   We need only the .kore file (parsed program and initial state);
    #   `--depth 0` stops without taking any steps, printing the initial state.
    time_run krun -d "$BUILDDIR" bench/sum.imp --depth 0 \
        --output kore > "$BUILDDIR"/sum.kore
    echo "───── interpreter"
    (   cd "$BUILDDIR"
        #   Iteration count hard-coded into sum.imp.
        time_run ./interpreter ./sum.kore -1 sum.output
    )
}

####################################################################

PROJDIR=$(command cd "$(dirname "$0")/.." && pwd -P)
BUILDDIR="$PROJDIR"/.build/bench/imp-kompiled

skip_compile=false
while [[ $# -gt 0 ]]; do case "$1" in                   # options
    -s|--skip-kompile)  shift; skip_compile=true;;
    --)                 shift; break;;
    -*)                 die 2 "Unknown option: $1";;
    *)                  break;;
esac; done
[[ $# -eq 1 ]] || die 2 "error: One parameter required."

command cd "$PROJDIR"
case "$1" in                                            # parameters
    k)  benchmark_k;;
    h)  benchmark_h;;
    *)  die 2 "Unknown benchmark type '$1': use 'h'=Haskell, 'k'=K"
esac
