{-  Syntax and Semantics of Mini-C.

    A greatly simplified subset of C.
-}

{-# OPTIONS_GHC -Wno-unused-top-binds #-}
module MiniC (
    -- datatypes and helpers
      Pgm (..), State (..), KItem (..)
    , AExp (..), BExp (..), Stmts (..), Block (..)
    , isReducedAExp, isReducedBExp
    , getK, putK, getStore, putStore
    , mkStmts
    , miniCInitState
    -- interpreters
    , eval_miniC
) where

import Prelude hiding (negate, div)
import qualified Prelude (div)
import Data.Map (Map, findWithDefault, fromList, insert, member)

import Rewrite.Class
import Rewrite.Basic

{----------------------------------------------------------------------
    Abstract Syntax

    Extension of Imp Syntax in Tarnyq.
-}

type Id     = String            -- In K, supplied by DOMAINS-SYNTAX.

data AExp   = Int !Integer
            | Var Id
            | Negate Integer    -- Cannot negate AExps for some reason.
            | AExp :/ AExp
         -- | Parens AExp       -- Needed for concrete syntax only.
            | AExp :+ AExp
            -- "Heating" rewrite rules generate a "hole" as a placeholder
            -- for an extracted expression that we are reducing. Once fully
            -- evaluated, a "cooling" rule will plug that normal form back
            -- into the hole. (In K, these are automatically generated by
            -- the strict/seqstrict attributes.)
            | AHole

data BExp   = Bool Bool
            | AExp :<= AExp
            | Not BExp
         -- | Parens BExp       -- Needed for concrete syntax only.
            | BExp :&& BExp
            | BHole             -- As per AHole above.

data Block  = StmtsBlock Stmts  -- Renamed from 'Stmt' in KTutImp
            | EmptyBlock
data Stmts  = Block Block
            | Id := AExp
            | If BExp Block Block
            | While BExp Block
            | StPair Stmts Stmts

data Pgm    = Pgm Ids Stmts
type Ids    = [Id]

                                -- Same precedence values as the prelude.
infixl 7  :/
infix  6  :+                    -- KTutImp: Left-assoc for more efficient parsing.
infix  4  :<=
infixl 3  :&&                   -- Should be RA! But broken this way in KTutImp.

--  The KTutImp parser doesn't produce a list of statements, but instead,
--  via right-associative parsing, produces a left-skewing nearly
--  degenerate binary tree. (Yes, this is weird, but a consequence of
--  'Stmts' rather than 'Block' being the root of the AST; a 'Stmts' must
--  be able to act like 'Block'.)
--  We provide this helper function to do the same thing as the KTutImp parser.
mkStmts :: [Stmts] -> Stmts
mkStmts stmtList = statements (reverse stmtList)  where
    statements []     = error "programs must have at least one statement"
    statements [s]    = s
    statements (s:ss) = StPair (statements ss) s


----------------------------------------------------------------------
-- State

data State = State { k :: K, store :: Store }  deriving Show

type K = [KItem]
data KItem = KI_Stmts Stmts
           | KI_AExp AExp
           | KI_BExp BExp
           deriving Show

type Store = Map Id Integer

--  Make all this showable just for convenience and debugging.
deriving instance Show AExp
deriving instance Show BExp
deriving instance Show Block
deriving instance Show Stmts    -- Not a list, so 'showList' override pointless.
deriving instance Show Pgm

deriving instance Eq AExp
deriving instance Eq BExp
deriving instance Eq Block
deriving instance Eq Stmts
deriving instance Eq KItem
deriving instance Eq State

----------------------------------------------------------------------
-- Initialization

miniCInitState :: Pgm -> State
miniCInitState (Pgm ids pgm) = State [KI_Stmts pgm] (miniCInitStore ids)

miniCInitStore :: [Id] -> Store
miniCInitStore ids = fromList $ zip ids (repeat 0)


----------------------------------------------------------------------
-- These can be auto-generated for each language state, using either
-- a custom `derive` attribute and/or Template Haskell.

-- K
getK :: MonadRewrite m State => m K
getK = do (State k _) <- get
          pure k

putK :: MonadRewrite m State =>  K -> m ()
putK k = do store <- getStore
            put (State k store)

-- Store
getStore :: MonadRewrite m State => m Store
getStore = do (State _ store) <- get
              pure store

putStore :: MonadRewrite m State => Store -> m ()
putStore store = do k <- getK
                    put (State k store)

---------------------------------------------------------------------
-- These are useful for defining heating rules

isReducedAExp :: AExp -> Bool
isReducedAExp (Int _)   = True
isReducedAExp _         = False

isReducedBExp :: BExp -> Bool
isReducedBExp (Bool _)  = True
isReducedBExp _         = False

---------------------------------------------------------------------
-- Semantics
eval_miniC :: Pgm -> State
eval_miniC pgm = evalOnePath miniC $ miniCInitState pgm

evalAllPaths_miniC :: Pgm -> [State]
evalAllPaths_miniC pgm = evalAllPaths miniC $ miniCInitState pgm


----------------------------------------------------------------------
-- Rules

miniC :: MonadRewrite m State =>  [m ()]
{-# INLINE miniC #-}
miniC =   [ assignHeat, assignCool, assign
        , lookupVar
        , seqStmt
        , while
        , ifHeat, ifCool, ifT, ifF
        , notHeat, notCool, notBExp
        , leHeatL, leCoolL, leHeatR, leCoolR , le
        , addHeatL, addCoolL, addHeatR, addCoolR, add
        , divHeatL, divCoolL, divHeatR, divCoolR, div
        , negate
        , block
        , emptyBlock
        ]


seqStmt :: MonadRewrite m State => m ()
{-# INLINE seqStmt #-}
seqStmt = do ((KI_Stmts (StPair s1 s2)):rest) <- getK
             putK $ (KI_Stmts s1):(KI_Stmts $ s2):rest

assign :: MonadRewrite m State => m ()
{-# INLINE assign #-}
assign = do ((KI_Stmts (id := Int i)):rest) <- getK
            store <- getStore
            putK rest
            putStore (insert id i store)

assignHeat :: MonadRewrite m State => m ()
{-# INLINE assignHeat #-}
assignHeat =
    do  ((KI_Stmts (id := aexp)):rest) <- getK
        guard $ not (isReducedAExp aexp)
        putK $ (KI_AExp aexp):(KI_Stmts (id := AHole)):rest

assignCool :: MonadRewrite m State => m ()
{-# INLINE assignCool #-}
assignCool =
    do  ((KI_AExp (Int i)):(KI_Stmts (id := AHole)):rest) <- getK
        putK $ (KI_Stmts (id := (Int i))):rest

while :: MonadRewrite m State => m ()
{-# INLINE while #-}
while = do (KI_Stmts (While cond body)):rest <- getK
           putK $ (KI_Stmts (If cond
                                (StmtsBlock $ StPair (Block body)
                                                     (While cond body))
                                EmptyBlock))
                  :rest

ifT :: MonadRewrite m State => m ()
{-# INLINE ifT #-}
ifT = do (KI_Stmts (If (Bool True) stmtsTrue _)):rest <- getK
         putK $ (KI_Stmts (Block stmtsTrue)):rest

ifF :: MonadRewrite m State => m ()
{-# INLINE ifF #-}
ifF = do (KI_Stmts (If (Bool False) _ stmtsFalse)):rest <- getK
         putK $ (KI_Stmts (Block stmtsFalse)):rest

ifHeat :: MonadRewrite m State => m ()
{-# INLINE ifHeat #-}
ifHeat = do ((KI_Stmts (If cond stmtsTrue stmtsFalse)):rest) <- getK
            guard $ not (isReducedBExp cond)
            putK $ (KI_BExp cond):
                    (KI_Stmts (If BHole stmtsTrue stmtsFalse)):rest

ifCool :: MonadRewrite m State => m ()
{-# INLINE ifCool #-}
ifCool = do ((KI_BExp (Bool b)):
                (KI_Stmts (If BHole stmtsTrue stmtsFalse)):rest) <- getK
            putK $ (KI_Stmts (If (Bool b) stmtsTrue stmtsFalse)):rest

notHeat :: MonadRewrite m State => m ()
{-# INLINE notHeat #-}
notHeat = do ((KI_BExp (Not bexp)):rest) <- getK
             guard $ not (isReducedBExp bexp)
             putK $ (KI_BExp bexp):(KI_BExp (Not BHole)):rest

notCool :: MonadRewrite m State => m ()
{-# INLINE notCool #-}
notCool = do ((KI_BExp (Bool b)):(KI_BExp (Not BHole)):rest) <- getK
             putK $ (KI_BExp (Not (Bool b))):rest

notBExp :: MonadRewrite m State => m ()
{-# INLINE notBExp #-}
notBExp = do (KI_BExp (Not (Bool b))):rest <- getK
             putK $  (KI_BExp (Bool (not b))):rest

leHeatL :: MonadRewrite m State => m ()
{-# INLINE leHeatL #-}
leHeatL = do ((KI_BExp (lhs :<= rhs)):rest) <- getK
             guard $ not (isReducedAExp lhs)
             putK $ (KI_AExp lhs):(KI_BExp (AHole :<= rhs)):rest

leCoolL :: MonadRewrite m State => m ()
{-# INLINE leCoolL #-}
leCoolL = do ((KI_AExp (Int i)):(KI_BExp (AHole :<= rhs)):rest) <- getK
             putK $ (KI_BExp (Int i :<= rhs)):rest

leHeatR :: MonadRewrite m State => m ()
{-# INLINE leHeatR #-}
leHeatR = do ((KI_BExp (lhs :<= rhs)):rest) <- getK
             guard $ (isReducedAExp lhs) && (not $ isReducedAExp rhs)
             putK $ (KI_AExp rhs):(KI_BExp (lhs :<= AHole)):rest

leCoolR :: MonadRewrite m State => m ()
{-# INLINE leCoolR #-}
leCoolR = do ((KI_AExp (Int i)):(KI_BExp (lhs :<= AHole)):rest) <- getK
             putK $ (KI_BExp (lhs :<= Int i)):rest

le :: MonadRewrite m State => m ()
{-# INLINE le #-}
le = do (KI_BExp (Int i :<= Int j)):rest <- getK
        putK $ (KI_BExp (Bool (i <= j))):rest

addHeatL :: MonadRewrite m State => m ()
{-# INLINE addHeatL #-}
addHeatL = do ((KI_AExp (lhs :+ rhs)):rest) <- getK
              guard $ not (isReducedAExp lhs)
              putK $ (KI_AExp lhs):(KI_AExp (AHole :+ rhs)):rest

addCoolL :: MonadRewrite m State => m ()
{-# INLINE addCoolL #-}
addCoolL = do ((KI_AExp (Int i)):(KI_AExp (AHole :+ rhs)):rest) <- getK
              putK $ (KI_AExp (Int i :+ rhs)):rest

addHeatR :: MonadRewrite m State => m ()
{-# INLINE addHeatR #-}
addHeatR = do ((KI_AExp (lhs :+ rhs)):rest) <- getK
              guard $ (isReducedAExp lhs) && (not $ isReducedAExp rhs)
              putK $ (KI_AExp rhs):(KI_AExp (lhs :+ AHole)):rest

addCoolR :: MonadRewrite m State => m ()
{-# INLINE addCoolR #-}
addCoolR = do ((KI_AExp (Int i)):(KI_AExp (lhs :+ AHole)):rest) <- getK
              putK $ (KI_AExp (lhs :+ Int i)):rest

add :: MonadRewrite m State => m ()
{-# INLINE add #-}
add = do (KI_AExp (Int i :+ Int j)):rest <- getK
         putK $ (KI_AExp (Int $ i + j)):rest

divHeatL :: MonadRewrite m State => m ()
{-# INLINE divHeatL #-}
divHeatL = do ((KI_AExp (lhs :/ rhs)):rest) <- getK
              guard $ not (isReducedAExp lhs)
              putK $ (KI_AExp lhs):(KI_AExp (AHole :/ rhs)):rest

divCoolL :: MonadRewrite m State => m ()
{-# INLINE divCoolL #-}
divCoolL = do ((KI_AExp (Int i)):(KI_AExp (AHole :/ rhs)):rest) <- getK
              putK $ (KI_AExp (Int i :/ rhs)):rest

divHeatR :: MonadRewrite m State => m ()
{-# INLINE divHeatR #-}
divHeatR = do ((KI_AExp (lhs :/ rhs)):rest) <- getK
              guard $ (isReducedAExp lhs) && (not $ isReducedAExp rhs)
              putK $ (KI_AExp rhs):(KI_AExp (lhs :/ AHole)):rest

divCoolR :: MonadRewrite m State => m ()
{-# INLINE divCoolR #-}
divCoolR = do ((KI_AExp (Int i)):(KI_AExp (lhs :/ AHole)):rest) <- getK
              putK $ (KI_AExp (lhs :/ Int i)):rest

div :: MonadRewrite m State => m ()
{-# INLINE div #-}
div = do (KI_AExp (Int i :/ Int j)):rest <- getK
         guard $ j /= 0
         putK $ (KI_AExp (Int $ i `Prelude.div` j)):rest

negate :: MonadRewrite m State => m ()
{-# INLINE negate #-}
negate = do (KI_AExp (Negate i)):rest <- getK
            putK $ (KI_AExp (Int (-1 * i))):rest

lookupVar :: MonadRewrite m State => m ()
{-# INLINE lookupVar #-}
lookupVar = do ((KI_AExp (Var x)):rest) <- getK
               store <- getStore
               guard $ member x store
               let exp = KI_AExp $ Int $ findWithDefault undefined x store in
                 put $ State (exp:rest) store

block :: MonadRewrite m State => m ()
{-# INLINE block #-}
block = do (KI_Stmts (Block (StmtsBlock s))):rest <- getK
           putK $ (KI_Stmts s):rest

emptyBlock :: MonadRewrite m State => m ()
{-# INLINE emptyBlock #-}
emptyBlock = do ((KI_Stmts (Block EmptyBlock)):rest) <- getK
                putK rest

