{-  Abstract syntax and semantics for the K tutorial 'Imp' language.
-}

{-# OPTIONS_GHC -Wno-unused-top-binds #-}

-- Needed for Show instances over DomainValue
{-# LANGUAGE UndecidableInstances #-}

module SymbolicImp (
      evalAllPaths_imp_symbolic                 -- interpreters
    , sum_imp_symbolic                          -- sample programs
    ) where

import Prelude hiding (negate)
import Data.SBV (Symbolic)
import Data.Map (Map, findWithDefault, fromList, insert, member)

import Rewrite.Class
import Rewrite.Symbolic


{----------------------------------------------------------------------
    Abstract Syntax

    This is almost exactly parallel (including the textual ordering and
    format) to 'module IMP-SYNTAX' in K except that, since it directly
    builds an AST, we leave out things such as parens that are relevant
    only to parsing text to an AST and strictness annotations that are
    actually part of the semantics. (We do however, for convenience,
    keep the precedence settings, both to document them and because it's
    handy when building an AST in Haskell code.)

    We also add 'Read' and 'Print' to the syntax. The semantics for
    these operations are only implemented in 'imp_io', and not 'imp'

    Below we refer to the semantics as written in K as 'KTutImp'.
-}

type Id     = String            -- In K, supplied by DOMAINS-SYNTAX.

data AExp dv = Int (dv Integer)
             | Var Id
             | Negate (dv Integer)     -- the tutorial does not allow negating
                                 --   arbritrary AExps for some reason?
             | (AExp dv) :/ (AExp dv)
          -- | Parens AExp       -- Needed for concrete syntax only.
             | (AExp dv) :+ (AExp dv)

             | Read              -- Only given a semantics in imp_io

             -- "Heating" rewrite rules generate a "hole" as a placeholder
             -- for an extracted expression that we are reducing. Once fully
             -- evaluated, a "cooling" rule will plug that normal form back
             -- into the hole. (In K, these are automatically generated by
             -- the strict/seqstrict attributes.)
             | AHole
deriving instance (Show (dv Integer), Show (dv Bool))
    => Show (AExp dv)

data BExp dv = Bool (dv Bool)
             | (AExp dv) :<= (AExp dv)
             | Not (BExp dv)
          -- | Parens BExp       -- Needed for concrete syntax only.
             | (BExp dv) :&& (BExp dv)
             | BHole             -- As per AHole above.
deriving instance (Show (dv Integer), Show (dv Bool))
    => Show (BExp dv)

data Block dv = StmtsBlock (Stmts  dv)
                                -- Renamed from 'Stmt' in KTutImp
             | EmptyBlock
deriving instance (Show (dv Integer), Show (dv Bool))
    => Show (Block dv)

data Stmts dv = Block (Block dv)
             | Id := (AExp dv)
             | If (BExp dv) (Block dv) (Block dv)
             | While (BExp dv) (Block dv)
             | StPair (Stmts dv) (Stmts dv)

             | Print (AExp dv)      -- Only given a semantics in 'imp_io'
deriving instance (Show (dv Integer), Show (dv Bool))
    => Show (Stmts dv)

data Pgm dv  = Pgm Ids (Stmts dv)
deriving instance (Show (dv Integer), Show (dv Bool))
    => Show (Pgm dv)

type Ids    = [Id]

                                -- Same precedence values as the prelude.
infixl 7  :/
infix  6  :+                    -- KTutImp: Left-assoc for more efficient parsing.
infix  4  :<=
infixl 3  :&&                   -- Should be RA! But broken this way in KTutImp.

--  The KTutImp parser doesn't produce a list of statements, but instead,
--  via right-associative parsing, produces a left-skewing nearly
--  degenerate binary tree. (Yes, this is weird, but a consequence of
--  'Stmts' rather than 'Block' being the root of the AST; a 'Stmts' must
--  be able to act like 'Block'.)
--  We provide this helper function to do the same thing as the KTutImp parser.
mkStmts :: [Stmts dv] -> Stmts dv
mkStmts stmtList = statements (reverse stmtList)  where
    statements []     = error "programs must have at least one statement"
    statements [s]    = s
    statements (s:ss) = StPair (statements ss) s


----------------------------------------------------------------------
-- State

data State dv = State { k :: K dv, store :: Store dv}
deriving instance (Show (dv Integer), Show (dv Bool))
    => Show (State dv)

type K dv = [KItem dv]
data KItem dv = KI_Stmts (Stmts dv)
             | KI_AExp (AExp dv)
             | KI_BExp (BExp dv)
deriving instance (Show (dv Integer), Show (dv Bool)) => Show (KItem dv)

type Store dv = Map Id (dv Integer)


----------------------------------------------------------------------
-- Initialization

impInitState :: DomainValue dv => (Pgm dv) -> (State dv)
impInitState (Pgm ids pgm) = State [KI_Stmts pgm] (impInitStore ids)

impInitStore :: DomainValue dv => [Id] -> (Store dv)
impInitStore ids = fromList $ zip ids (repeat $ dInteger 0)


----------------------------------------------------------------------
-- These can be auto-generated for each language state, using either
-- a custom `derive` attribute and/or Template Haskell.

-- K
getK :: MonadRewrite m dv (State dv) => m (K dv)
getK = do (State k _) <- get
          pure k

putK :: MonadRewrite m dv (State dv) =>  (K dv) -> m ()
putK k = do store <- getStore
            put (State k store)

-- Store
getStore :: MonadRewrite m dv (State dv) => m (Store dv)
getStore = do (State _ store) <- get
              pure store

putStore :: MonadRewrite m dv (State dv) => (Store dv) -> m ()
putStore store = do k <- getK
                    put (State k store)

---------------------------------------------------------------------
-- These are useful for defining heating rules

isReducedAExp :: AExp dv -> Bool
isReducedAExp (Int _)   = True
isReducedAExp _         = False

isReducedBExp :: BExp dv -> Bool
isReducedBExp (Bool _)  = True
isReducedBExp _         = False

---------------------------------------------------------------------
-- Semantics
-- If this is expanded in other files, it may lose the inlining
-- unless 'imp' is marked INLINE.

evalAllPaths_imp_symbolic :: (Pgm SymbolicExpr) -> Symbolic [Constrained (State SymbolicExpr)]
evalAllPaths_imp_symbolic pgm = evalAllPathsSymbolic imp_symbolic $ impInitState pgm

----------------------------------------------------------------------
-- Rules

imp_symbolic :: MonadRewrite m dv (State dv) =>  [m ()]
{-# INLINE imp_symbolic #-}
imp_symbolic =
        [ assignHeat, assignCool, assign
        , lookupVar
        , seqStmt
        , while
        , ifHeat, ifCool, ifT, ifF
        , notHeat, notCool, notBExp
        , leHeatL, leCoolL, leHeatR, leCoolR , le
        , addHeatL, addCoolL, addHeatR, addCoolR, add
        , divHeatL, divCoolL, divHeatR, divCoolR -- , SymbolicImp.div
        , negate
        , block
        , emptyBlock
        ]

seqStmt :: MonadRewrite m dv (State dv) => m ()
seqStmt = do ((KI_Stmts (StPair s1 s2)):rest) <- getK
             putK $ (KI_Stmts s1):(KI_Stmts $ s2):rest

assign :: MonadRewrite m dv (State dv) => m ()
assign = do ((KI_Stmts (id := Int i)):rest) <- getK
            store <- getStore
            putK rest
            putStore (insert id i store)

assignHeat :: MonadRewrite m dv (State dv) => m ()
assignHeat =
    do  ((KI_Stmts (id := aexp)):rest) <- getK
        guard $ not (isReducedAExp aexp)
        putK $ (KI_AExp aexp):(KI_Stmts (id := AHole)):rest

assignCool :: MonadRewrite m dv (State dv) => m ()
assignCool =
    do  ((KI_AExp (Int i)):(KI_Stmts (id := AHole)):rest) <- getK
        putK $ (KI_Stmts (id := (Int i))):rest

while :: MonadRewrite m dv (State dv) => m ()
while = do (KI_Stmts (While cond body)):rest <- getK
           putK $ (KI_Stmts (If cond
                                (StmtsBlock $ StPair (Block body)
                                                     (While cond body))
                                EmptyBlock))
                  :rest

ifT :: MonadRewrite m dv (State dv) => m ()
ifT = do (KI_Stmts (If (Bool cond) stmtsTrue _)):rest <- getK
         sguard cond
         putK $ (KI_Stmts (Block stmtsTrue)):rest

ifF :: MonadRewrite m dv (State dv) => m ()
ifF = do (KI_Stmts (If (Bool cond) _ stmtsFalse)):rest <- getK
         sguard (dNot cond)
         putK $ (KI_Stmts (Block stmtsFalse)):rest

ifHeat :: MonadRewrite m dv (State dv) => m ()
ifHeat = do ((KI_Stmts (If cond stmtsTrue stmtsFalse)):rest) <- getK
            guard $ not (isReducedBExp cond)
            putK $ (KI_BExp cond):
                    (KI_Stmts (If BHole stmtsTrue stmtsFalse)):rest

ifCool :: MonadRewrite m dv (State dv) => m ()
ifCool = do ((KI_BExp (Bool b)):
                (KI_Stmts (If BHole stmtsTrue stmtsFalse)):rest) <- getK
            putK $ (KI_Stmts (If (Bool b) stmtsTrue stmtsFalse)):rest

notHeat :: MonadRewrite m dv (State dv) => m ()
notHeat = do ((KI_BExp (Not bexp)):rest) <- getK
             guard $ not (isReducedBExp bexp)
             putK $ (KI_BExp bexp):(KI_BExp (Not BHole)):rest

notCool :: MonadRewrite m dv (State dv) => m ()
notCool = do ((KI_BExp (Bool b)):(KI_BExp (Not BHole)):rest) <- getK
             putK $ (KI_BExp (Not (Bool b))):rest

notBExp :: MonadRewrite m dv (State dv) => m ()
notBExp = do (KI_BExp (Not (Bool b))):rest <- getK
             putK $ (KI_BExp (Bool (dNot b))):rest

leHeatL :: MonadRewrite m dv (State dv) => m ()
leHeatL = do ((KI_BExp (lhs :<= rhs)):rest) <- getK
             guard $ not (isReducedAExp lhs)
             putK $ (KI_AExp lhs):(KI_BExp (AHole :<= rhs)):rest

leCoolL :: MonadRewrite m dv (State dv) => m ()
leCoolL = do ((KI_AExp (Int i)):(KI_BExp (AHole :<= rhs)):rest) <- getK
             putK $ (KI_BExp (Int i :<= rhs)):rest

leHeatR :: MonadRewrite m dv (State dv) => m ()
leHeatR = do ((KI_BExp (lhs :<= rhs)):rest) <- getK
             guard $ (isReducedAExp lhs) && (not $ isReducedAExp rhs)
             putK $ (KI_AExp rhs):(KI_BExp (lhs :<= AHole)):rest

leCoolR :: MonadRewrite m dv (State dv) => m ()
leCoolR = do ((KI_AExp (Int i)):(KI_BExp (lhs :<= AHole)):rest) <- getK
             putK $ (KI_BExp (lhs :<= Int i)):rest

le :: MonadRewrite m dv (State dv) => m ()
le = do (KI_BExp (Int i :<= Int j)):rest <- getK
        putK $ (KI_BExp (Bool (lt i j))):rest

addHeatL :: MonadRewrite m dv (State dv) => m ()
addHeatL = do ((KI_AExp (lhs :+ rhs)):rest) <- getK
              guard $ not (isReducedAExp lhs)
              putK $ (KI_AExp lhs):(KI_AExp (AHole :+ rhs)):rest

addCoolL :: MonadRewrite m dv (State dv) => m ()
addCoolL = do ((KI_AExp (Int i)):(KI_AExp (AHole :+ rhs)):rest) <- getK
              putK $ (KI_AExp (Int i :+ rhs)):rest

addHeatR :: MonadRewrite m dv (State dv) => m ()
addHeatR = do ((KI_AExp (lhs :+ rhs)):rest) <- getK
              guard $ (isReducedAExp lhs) && (not $ isReducedAExp rhs)
              putK $ (KI_AExp rhs):(KI_AExp (lhs :+ AHole)):rest

addCoolR :: MonadRewrite m dv (State dv) => m ()
addCoolR = do ((KI_AExp (Int i)):(KI_AExp (lhs :+ AHole)):rest) <- getK
              putK $ (KI_AExp (lhs :+ Int i)):rest

add :: MonadRewrite m dv (State dv) => m ()
add = do (KI_AExp (Int i :+ Int j)):rest <- getK
         putK $ (KI_AExp (Int $ dAdd i j)):rest

divHeatL :: MonadRewrite m dv (State dv) => m ()
divHeatL = do ((KI_AExp (lhs :/ rhs)):rest) <- getK
              guard $ not (isReducedAExp lhs)
              putK $ (KI_AExp lhs):(KI_AExp (AHole :/ rhs)):rest

divCoolL :: MonadRewrite m dv (State dv) => m ()
divCoolL = do ((KI_AExp (Int i)):(KI_AExp (AHole :/ rhs)):rest) <- getK
              putK $ (KI_AExp (Int i :/ rhs)):rest

divHeatR :: MonadRewrite m dv (State dv) => m ()
divHeatR = do ((KI_AExp (lhs :/ rhs)):rest) <- getK
              guard $ (isReducedAExp lhs) && (not $ isReducedAExp rhs)
              putK $ (KI_AExp rhs):(KI_AExp (lhs :/ AHole)):rest

divCoolR :: MonadRewrite m dv (State dv) => m ()
divCoolR = do ((KI_AExp (Int i)):(KI_AExp (lhs :/ AHole)):rest) <- getK
              putK $ (KI_AExp (lhs :/ Int i)):rest

div :: MonadRewrite m dv (State dv) => m ()
div = do (KI_AExp (Int i :/ Int j)):rest <- getK
         sguard $ j `dNEq` (dInteger 0)
         putK $ (KI_AExp (Int $ i `dDiv` j)):rest

negate :: MonadRewrite m dv (State dv) => m ()
negate = do (KI_AExp (Negate i)):rest <- getK
            putK $ (KI_AExp (Int (dMul (dInteger $ -1) i))):rest

lookupVar :: MonadRewrite m dv (State dv) => m ()
lookupVar = do ((KI_AExp (Var x)):rest) <- getK
               store <- getStore
               guard $ member x store
               let exp = KI_AExp $ Int $ findWithDefault undefined x store in
                 put $ State (exp:rest) store

block :: MonadRewrite m dv (State dv) => m ()
block = do (KI_Stmts (Block (StmtsBlock s))):rest <- getK
           putK $ (KI_Stmts s):rest

emptyBlock :: MonadRewrite m dv (State dv) => m ()
emptyBlock = do ((KI_Stmts (Block EmptyBlock)):rest) <- getK
                putK rest

----------------------------------------------------------------------
--  Sample programs to test syntax and semantics.
--
--  ./Test  -m KTutImp -e 'mapM print $ map eval_imp […]'
--      (where … = sum_imp, divide_imp, div0_imp)
--  (Eventually Test will be able find all of the `x :: Pgm` here
--  and evaluate them all for you.)

sum_imp_symbolic :: (SymbolicExpr Integer) -> (Pgm SymbolicExpr)
                                                            --  'sum.imp'
sum_imp_symbolic n = Pgm ids stmts  where
    ids   = ["n", "sum"]                                    --  int n, sum
    stmts = mkStmts                                         --
          [ "n" := Int n                                    --  n = $n
          , "sum" := (Int $ dInteger 0)                     --  sum = 0
          , While (Not (Var "n" :<= (Int $ dInteger 0)))    --  while (!(n <= 0)) {
               (StmtsBlock (mkStmts                         --
                 [ "sum" := (Var "sum" :+ Var "n")          --    sum = sum + n
                 , "n" := (Var "n" :+ Negate (dInteger 1))  --    n = n + -1
                 ]))                                        --  }
          ]
