{-  Abstract syntax and semantics for the K tutorial 'Imp' language.

    (This would normally be in a separate repo that uses this library,
    but it's here while we do development on the framework.)

    This is a translation to KMonad of the K syntax and semantics for the
    Imp programming language and associated examples from the K
    Tutorial[1]. There is a separate implementation of Imp in the
    imp-semantics repo[2] which is not the same.

    [1]: https://github.com/runtimeverification/pl-tutorial/blob/master/1_k/2_imp/lesson_5/imp.md
    [2]: https://github.com/runtimeverification/imp-semantics
-}

{-# OPTIONS_GHC -Wno-unused-top-binds #-}
module KTutImp
    ( Pgm (..), State (..), AExp (..), BExp (..), Block (..), KItem (..), Stmts (..)
    , eval_imp                          -- interpreter
    , sum_imp, divide_imp, div0_imp     -- sample programs
    , eval_sum
    ) where

import Prelude hiding (negate, div, print)
import qualified Prelude (div)
import Data.Map (Map, findWithDefault, fromList, insert, member)

import Tarnyq

{----------------------------------------------------------------------
    Abstract Syntax

    This is almost exactly parallel (including the textual ordering and
    format) to 'module IMP-SYNTAX' in K except that, since it directly
    builds an AST, we leave out things such as parens that are relevant
    only to parsing text to an AST and strictness annotations that are
    actually part of the semantics. (We do however, for convenience,
    keep the precedence settings, both to document them and because it's
    handy when building an AST in Haskell code.)

    Below we refer to the semantics as written in K as 'KTutImp'.
-}

type Id     = String            -- In K, supplied by DOMAINS-SYNTAX.

data AExp   = Int !Integer
            | Var Id
            | Negate Integer    -- Cannot negate AExps for some reason.
            | AExp :/ AExp
         -- | Parens AExp       -- Needed for concrete syntax only.
            | AExp :+ AExp
            -- "Heating" rewrite rules generate a "hole" as a placeholder
            -- for an extracted expression that we are reducing. Once fully
            -- evaluated, a "cooling" rule will plug that normal form back
            -- into the hole. (In K, these are automatically generated by
            -- the strict/seqstrict attributes.)
            | AHole

data BExp   = Bool Bool
            | AExp :<= AExp
            | Not BExp
         -- | Parens BExp       -- Needed for concrete syntax only.
            | BExp :&& BExp
            | BHole             -- As per AHole above.

data Block  = StmtsBlock Stmts  -- Renamed from 'Stmt' in KTutImp
            | EmptyBlock
data Stmts  = Block Block
            | Id := AExp
            | If BExp Block Block
            | While BExp Block
            | StPair Stmts Stmts
            | Print AExp

data Pgm    = Pgm Ids Stmts
type Ids    = [Id]

                                -- Same precedence values as the prelude.
infixl 7  :/
infix  6  :+                    -- KTutImp: Left-assoc for more efficient parsing.
infix  4  :<=
infixl 3  :&&                   -- Should be RA! But broken this way in KTutImp.

--  The KTutImp parser doesn't produce a list of statements, but instead,
--  via right-associative parsing, produces a left-skewing nearly
--  degenerate binary tree. (Yes, this is weird, but a consequence of
--  'Stmts' rather than 'Block' being the root of the AST; a 'Stmts' must
--  be able to act like 'Block'.)
--  We provide this helper function to do the same thing as the KTutImp parser.
mkStmts :: [Stmts] -> Stmts
mkStmts stmtList = statements (reverse stmtList)  where
    statements []     = error "programs must have at least one statement"
    statements [s]    = s
    statements (s:ss) = StPair (statements ss) s


----------------------------------------------------------------------
-- State

data State = State { k :: K, store :: Store }  deriving Show

type K = [KItem]
data KItem = KI_Stmts Stmts
           | KI_AExp AExp
           | KI_BExp BExp
           deriving Show

type Store = Map Id Integer

--  Make all this showable just for convenience and debugging.
deriving instance Show AExp
deriving instance Show BExp
deriving instance Show Block
deriving instance Show Stmts    -- Not a list, so 'showList' override pointless.
deriving instance Show Pgm

deriving instance Eq AExp
deriving instance Eq BExp
deriving instance Eq Block
deriving instance Eq Stmts
deriving instance Eq KItem
deriving instance Eq State

----------------------------------------------------------------------
-- Initialization

impInitState :: Pgm -> State
impInitState (Pgm ids pgm) = State [KI_Stmts pgm] (impInitStore ids)

impInitStore :: [Id] -> Store
impInitStore ids = fromList $ zip ids (repeat 0)


----------------------------------------------------------------------
-- These can be auto-generated for each language state, using either
-- a custom `derive` attribute and/or Template Haskell.

liftK :: MonadFail m => RewriteM m K a -> RewriteM m State a
liftK = mkLift (\state -> Just (k state, state))
               (\k state -> (state{k}))

matchStmt :: MonadFail m => RewriteM m State Stmts
matchStmt = do (State ((KI_Stmts stmt):_) _) <- get
               pure stmt

liftStmts :: MonadFail m => RewriteM m Stmts a -> RewriteM m State a
liftStmts = mkLift unplug plug where
    unplug = \case state@(State ((KI_Stmts s):rest) _) -> Just (s, (state, rest))
                   _                                   -> Nothing
    plug stmts (state, rest) = state{k=(KI_Stmts stmts):(rest)}

liftAExp :: MonadFail m => RewriteM m AExp a -> RewriteM m State a
liftAExp = mkLift unplug plug where
    unplug = \case state@(State ((KI_AExp s):rest) _) -> Just (s, (state, rest))
                   _                                   -> Nothing
    plug stmts (state, rest) = state{k=(KI_AExp stmts):(rest)}

liftBExp :: MonadFail m => RewriteM m BExp a -> RewriteM m State a
liftBExp = mkLift unplug plug where
    unplug = \case state@(State ((KI_BExp s):rest) _) -> Just (s, (state, rest))
                   _                                   -> Nothing
    plug stmts (state, rest) = state{k=(KI_BExp stmts):(rest)}

liftStore :: MonadFail m => RewriteM m Store a -> RewriteM m State a
liftStore = mkLift (\state -> Just (store state, state))
                   (\store state -> (state{store}))

-- Pulls out the store from the State, keeping the state unchanged.
getStore :: MonadFail m => RewriteM m State Store
getStore = liftStore get

putStore :: MonadFail m => Store -> RewriteM m State ()
putStore = liftStore . put

getK :: MonadFail m => RewriteM m State K
getK = liftK get

putK :: MonadFail m => K -> RewriteM m State ()
putK = liftK . put


---------------------------------------------------------------------
-- These are useful for defining heating rules

isInt :: AExp -> Bool
isInt (Int _) = True
isInt _       = False

isBool :: BExp -> Bool
isBool (Bool _) = True
isBool _       = False

---------------------------------------------------------------------
-- Semantics
-- If this is expanded in other files, it may lose the inlining
-- unless 'imp' is marked INLINE.
eval_imp :: Pgm -> State
eval_imp pgm = evalOnePath imp $ impInitState pgm


----------------------------------------------------------------------
-- Rules

imp :: MonadFail m => [Rewrite m State]
imp =   [ liftK     assignHeat
        , liftK     assignCool
        ,           assign
        ,           lookupVar
        , liftK     seqStmt
        , liftStmts while
        , liftK     ifHeat
        , liftK     ifCool
        , liftStmts ifT
        , liftStmts ifF
        , liftK     notHeat
        , liftK     notCool
        , liftBExp  notBExp
        , liftK     leHeatL
        , liftK     leCoolL
        , liftK     leHeatR
        , liftK     leCoolR
        , liftBExp  le
        , liftK     addHeatL
        , liftK     addCoolL
        , liftK     addHeatR
        , liftK     addCoolR
        , liftAExp  add
        , liftK     divHeatL
        , liftK     divCoolL
        , liftK     divHeatR
        , liftK     divCoolR
        , liftAExp  div
        , liftAExp  negate
        , liftStmts block
        , liftK     emptyBlock
        ]

seqStmt :: MonadFail m => Rewrite m K
seqStmt = do ((KI_Stmts (StPair s1 s2)):rest) <- get
             put $ (KI_Stmts s1):(KI_Stmts $ s2):rest

assign :: MonadFail m => Rewrite m State
assign = do ((KI_Stmts (id := Int i)):rest) <- getK
            store <- getStore
            putK rest
            putStore (insert id i store)

assignHeat :: MonadFail m => Rewrite m K
assignHeat =
    do  ((KI_Stmts (id := aexp)):rest) <- get
        guard $ not (isInt aexp)
        put $ (KI_AExp aexp):(KI_Stmts (id := AHole)):rest

assignCool :: MonadFail m => Rewrite m K
assignCool =
    do  ((KI_AExp (Int i)):(KI_Stmts (id := AHole)):rest) <- get
        put $ (KI_Stmts (id := (Int i))):rest

while :: MonadFail m => Rewrite m Stmts
while = do (While cond body) <- get
           put $ (If cond
                    (StmtsBlock $ StPair (Block body)
                                         (While cond body))
                    EmptyBlock)

ifT :: MonadFail m => Rewrite m Stmts
ifT = do (If (Bool True) stmtsTrue _) <- get
         put (Block stmtsTrue)

ifF :: MonadFail m => Rewrite m Stmts
ifF = do (If (Bool False) _ stmtsFalse) <- get
         put (Block stmtsFalse)

ifHeat :: MonadFail m => Rewrite m K
ifHeat = do ((KI_Stmts (If cond stmtsTrue stmtsFalse)):rest) <- get
            guard $ not (isBool cond)
            put $ (KI_BExp cond):
                    (KI_Stmts (If BHole stmtsTrue stmtsFalse)):rest

ifCool :: MonadFail m => Rewrite m K
ifCool = do ((KI_BExp (Bool b)):
                (KI_Stmts (If BHole stmtsTrue stmtsFalse)):rest) <- get
            put $ (KI_Stmts (If (Bool b) stmtsTrue stmtsFalse)):rest

notHeat :: MonadFail m => Rewrite m K
notHeat = do ((KI_BExp (Not bexp)):rest) <- get
             guard $ not (isBool bexp)
             put $ (KI_BExp bexp):(KI_BExp (Not BHole)):rest

notCool :: MonadFail m => Rewrite m K
notCool = do ((KI_BExp (Bool b)):(KI_BExp (Not BHole)):rest) <- get
             put $ (KI_BExp (Not (Bool b))):rest

notBExp :: MonadFail m => Rewrite m BExp
notBExp = do (Not (Bool b)) <- get
             put (Bool (not b))

leHeatL :: MonadFail m => Rewrite m K
leHeatL = do ((KI_BExp (lhs :<= rhs)):rest) <- get
             guard $ not (isInt lhs)
             put $ (KI_AExp lhs):(KI_BExp (AHole :<= rhs)):rest

leCoolL :: MonadFail m => Rewrite m K
leCoolL = do ((KI_AExp (Int i)):(KI_BExp (AHole :<= rhs)):rest) <- get
             put $ (KI_BExp (Int i :<= rhs)):rest

leHeatR :: MonadFail m => Rewrite m K
leHeatR = do ((KI_BExp (lhs :<= rhs)):rest) <- get
             guard $ not ((isInt lhs) && (isInt rhs))
             put $ (KI_AExp rhs):(KI_BExp (lhs :<= AHole)):rest

leCoolR :: MonadFail m => Rewrite m K
leCoolR = do ((KI_AExp (Int i)):(KI_BExp (lhs :<= AHole)):rest) <- get
             put $ (KI_BExp (lhs :<= Int i)):rest

le :: MonadFail m => Rewrite m BExp
le = do (Int i :<= Int j) <- get
        put $ (Bool (i <= j))

addHeatL :: MonadFail m => Rewrite m K
addHeatL = do ((KI_AExp (lhs :+ rhs)):rest) <- get
              guard $ not (isInt lhs)
              put $ (KI_AExp lhs):(KI_AExp (AHole :+ rhs)):rest

addCoolL :: MonadFail m => Rewrite m K
addCoolL = do ((KI_AExp (Int i)):(KI_AExp (AHole :+ rhs)):rest) <- get
              put $ (KI_AExp (Int i :+ rhs)):rest

addHeatR :: MonadFail m => Rewrite m K
addHeatR = do ((KI_AExp (lhs :+ rhs)):rest) <- get
              guard $ not ((isInt lhs) && (isInt rhs))
              put $ (KI_AExp rhs):(KI_AExp (lhs :+ AHole)):rest

addCoolR :: MonadFail m => Rewrite m K
addCoolR = do ((KI_AExp (Int i)):(KI_AExp (lhs :+ AHole)):rest) <- get
              put $ (KI_AExp (lhs :+ Int i)):rest

add :: MonadFail m => Rewrite m AExp
add = do (Int i :+ Int j) <- get
         put $ (Int $ i + j)

divHeatL :: MonadFail m => Rewrite m K
divHeatL = do ((KI_AExp (lhs :/ rhs)):rest) <- get
              guard $ not (isInt lhs)
              put $ (KI_AExp lhs):(KI_AExp (AHole :/ rhs)):rest

divCoolL :: MonadFail m => Rewrite m K
divCoolL = do ((KI_AExp (Int i)):(KI_AExp (AHole :/ rhs)):rest) <- get
              put $ (KI_AExp (Int i :/ rhs)):rest

divHeatR :: MonadFail m => Rewrite m K
divHeatR = do ((KI_AExp (lhs :/ rhs)):rest) <- get
              guard $ not ((isInt lhs) && (isInt rhs))
              put $ (KI_AExp rhs):(KI_AExp (lhs :/ AHole)):rest

divCoolR :: MonadFail m => Rewrite m K
divCoolR = do ((KI_AExp (Int i)):(KI_AExp (lhs :/ AHole)):rest) <- get
              put $ (KI_AExp (lhs :/ Int i)):rest

div :: MonadFail m => Rewrite m AExp
div = do (Int i :/ Int j) <- get
         guard $ j /= 0
         put (Int $ i `Prelude.div` j)

negate :: MonadFail m => Rewrite m AExp
negate = do (Negate i) <- get
            put $ Int (-1 * i)

lookupVar :: MonadFail m => Rewrite m State
lookupVar = do ((KI_AExp (Var x)):rest) <- getK
               store <- getStore
               guard $ member x store
               let exp = KI_AExp $ Int $ findWithDefault undefined x store in
                 put $ State (exp:rest) store

block :: MonadFail m => Rewrite m Stmts
block = do (Block (StmtsBlock s)) <- get
           put s

emptyBlock :: MonadFail m => Rewrite m K
emptyBlock = do ((KI_Stmts (Block EmptyBlock)):rest) <- get
                put rest


------------------------------------------------------------------------

class Monad m => Console m where
  print :: String -> m ()

instance Console m => Console (RewriteM m s) where
  print str = RewriteM $ \s -> do print str
                                  pure ((), s)

print_ :: (Console m, MonadFail m) => Rewrite m Stmts
print_ = do (Print (Int i)) <- get
            print (show i)

imp_io :: (Console m, MonadFail m) => [Rewrite m State]
imp_io = imp ++ [liftStmts print_]

----------------------------------------------------------------------
--  Sample programs to test syntax and semantics.
--
--  ./Test  -m KTutImp -e 'mapM print $ map eval_imp […]'
--      (where … = sum_imp, divide_imp, div0_imp)
--  (Eventually Test will be able find all of the `x :: Pgm` here
--  and evaluate them all for you.)

sum_imp :: Integer -> Pgm                           --  'sum.imp'
sum_imp n = Pgm ids stmts  where
    ids   = ["n", "sum"]                            --  int n, sum
    stmts = mkStmts                                 --
          [ "n" := Int n                            --  n = $n
          , "sum" := Int 0                          --  sum = 0
          , While (Not (Var "n" :<= (Int 0)))       --  while (!(n <= 0)) {
               (StmtsBlock (mkStmts                 --
                 [ "sum" := (Var "sum" :+ Var "n")  --    sum = sum + n
                 , "n" := (Var "n" :+ Negate 1)     --    n = n + -1
                 ]))                                --  }
          ]

divide_imp :: Pgm
divide_imp = Pgm ids stmts  where
    ids   = ["a", "b", "r"]                         --  int a, b, r
    stmts = mkStmts                                 --
          [ "a" := Int 100                          --  a = 100
          , "b" := Int 3                            --  b = 3
          , "r" := (Var "a" :/ Var "b")             --  r = a / b
          ]

div0_imp :: Pgm
div0_imp = Pgm ids stmts  where
    ids   = ["r"]
    stmts = mkStmts [ "r" := (Int 42 :/ Int 0) ]

---------------------------------------------------------------------
-- A Light-weight Semantics-based compilation.
-- By sequencing rules directly manually we get a light-weight
-- SBC. This gives us a 3x speedup. GHC isn't able to merge the rules
-- completely, likely because showing that the RHS and LHS of consecutive
-- is identical is non-trivial.
--
-- One advantage of this method is that it is correct "by-construction",
-- compared with full SBC produced through symbolic execution,
-- where completely new rules are generated.
-- This may make it a good bridge for proving correctness of full SBC.
--
-- My suspicsion is that if we were able to supply the substitutions
-- (i.e. break up the rewrite into a "match" and "apply" step, and
-- partially apply with known matching results),
-- function inlining would work even better, giving us a larger speed up.
--
-- This summarization was produced "manually", however, figuring out the
-- required sequences -- of rules needed can be done fairly easily via concrete
-- execution by having rewrite emit logs.

sum_imp_summary :: MonadFail m => [Rewrite m State]
sum_imp_summary = [whileTrueBranch, whileFalseBranch, initialize] where
        whileCondEval =
            (liftStmts while) >>  (liftK ifHeat) >> (liftK notHeat) >>
            (liftK leHeatL) >> lookupVar >> (liftK leCoolL) >> (liftBExp le) >>
            (liftK notCool) >> (liftBExp  notBExp) >> (liftK ifCool)
        whileTrueBranch = whileCondEval >>
            (liftStmts ifT) >> (liftStmts block) >> (liftK seqStmt) >>
            (liftStmts block) >> (liftK seqStmt) >> (liftK assignHeat) >>
            (liftK addHeatL) >> lookupVar >> (liftK addCoolL) >>
            (liftK addHeatR) >> lookupVar >> (liftK addCoolR) >>
            (liftAExp add) >> (liftK assignCool) >> assign >>
            (liftK assignHeat) >> (liftK addHeatL) >> lookupVar >>
            (liftK addCoolL) >> (liftK addHeatR) >> (liftAExp negate) >>
            (liftK addCoolR) >> (liftAExp add) >> (liftK assignCool) >> assign
        whileFalseBranch = whileCondEval >>
            (liftStmts ifF) >> (liftK emptyBlock)
        initialize = (liftK seqStmt) >> (liftK seqStmt) >> assign >> assign

eval_sum :: Integer -> State
eval_sum n = evalOnePath sum_imp_summary $ impInitState $ sum_imp n
