{-  Abstract syntax and semantics for the K tutorial 'Imp' language.

    (This would normally be in a separate repo that uses this library,
    but it's here while we do development on the framework.)

    This is a translation to KMonad of the K syntax and semantics for the
    Imp programming language and associated examples from the K
    Tutorial[1]. There is a separate implementation of Imp in the
    imp-semantics repo[2] which is not the same.

    [1]: https://github.com/runtimeverification/pl-tutorial/blob/master/1_k/2_imp/lesson_5/imp.md
    [2]: https://github.com/runtimeverification/imp-semantics
-}

{-# OPTIONS_GHC -Wno-unused-top-binds #-}
module KTutImp
    ( Pgm (..), State (..), AExp (..), BExp (..), Block (..), KItem (..), Stmts (..)
    , eval_imp                          -- interpreter
    , sum_imp, divide_imp, div0_imp     -- sample programs
    ) where

import Prelude hiding (negate, div)
import qualified Prelude (div)
import Data.Map (Map, findWithDefault, fromList, insert, member)

import Tarnyq

{----------------------------------------------------------------------
    Abstract Syntax

    This is almost exactly parallel (including the textual ordering and
    format) to 'module IMP-SYNTAX' in K except that, since it directly
    builds an AST, we leave out things such as parens that are relevant
    only to parsing text to an AST and strictness annotations that are
    actually part of the semantics. (We do however, for convenience,
    keep the precedence settings, both to document them and because it's
    handy when building an AST in Haskell code.)

    Below we refer to the semantics as written in K as 'KTutImp'.
-}

type Id     = String            -- In K, supplied by DOMAINS-SYNTAX.

data AExp   = Int !Integer
            | Var Id
            | Negate Integer    -- Cannot negate AExps for some reason.
            | AExp :/ AExp
         -- | Parens AExp       -- Needed for concrete syntax only.
            | AExp :+ AExp
            -- "Heating" rewrite rules generate a "hole" as a placeholder
            -- for an extracted expression that we are reducing. Once fully
            -- evaluated, a "cooling" rule will plug that normal form back
            -- into the hole. (In K, these are automatically generated by
            -- the strict/seqstrict attributes.)
            | AHole

data BExp   = Bool Bool
            | AExp :<= AExp
            | Not BExp
         -- | Parens BExp       -- Needed for concrete syntax only.
            | BExp :&& BExp
            | BHole             -- As per AHole above.

data Block  = StmtsBlock Stmts  -- Renamed from 'Stmt' in KTutImp
            | EmptyBlock
data Stmts  = Block Block
            | Id := AExp
            | If BExp Block Block
            | While BExp Block
            | StPair Stmts Stmts
data Pgm    = Pgm Ids Stmts
type Ids    = [Id]

                                -- Same precedence values as the prelude.
infixl 7  :/
infix  6  :+                    -- KTutImp: Left-assoc for more efficient parsing.
infix  4  :<=
infixl 3  :&&                   -- Should be RA! But broken this way in KTutImp.

--  The KTutImp parser doesn't produce a list of statements, but instead,
--  via right-associative parsing, produces a left-skewing nearly
--  degenerate binary tree. (Yes, this is weird, but a consequence of
--  'Stmts' rather than 'Block' being the root of the AST; a 'Stmts' must
--  be able to act like 'Block'.)
--  We provide this helper function to do the same thing as the KTutImp parser.
mkStmts :: [Stmts] -> Stmts
mkStmts stmtList = statements (reverse stmtList)  where
    statements []     = error "programs must have at least one statement"
    statements [s]    = s
    statements (s:ss) = StPair (statements ss) s


----------------------------------------------------------------------
-- State

data State = State { k :: K, store :: Store }  deriving Show

type K = [KItem]
data KItem = KI_Stmts Stmts
           | KI_AExp AExp
           | KI_BExp BExp
           deriving Show

type Store = Map Id Integer

--  Make all this showable just for convenience and debugging.
deriving instance Show AExp
deriving instance Show BExp
deriving instance Show Block
deriving instance Show Stmts    -- Not a list, so 'showList' override pointless.
deriving instance Show Pgm

deriving instance Eq AExp
deriving instance Eq BExp
deriving instance Eq Block
deriving instance Eq Stmts
deriving instance Eq KItem
deriving instance Eq State

----------------------------------------------------------------------
-- Initialization

impInitState :: Pgm -> State
impInitState (Pgm ids pgm) = State [KI_Stmts pgm] (impInitStore ids)

impInitStore :: [Id] -> Store
impInitStore ids = fromList $ zip ids (repeat 0)


----------------------------------------------------------------------
-- These can be auto-generated for each language state, using either
-- a custom `derive` attribute and/or template Haskell.

liftK :: RewriteM K a -> RewriteM State a
liftK (RewriteM f) = RewriteM $ \state -> case f (k state) of
                            Just (a, k') -> Just $ (a, state { k = k' })
                            Nothing      -> Nothing

liftStmts :: RewriteM Stmts a -> RewriteM State a
liftStmts (RewriteM f) =
    RewriteM $ \st -> case st of
                 (State ((KI_Stmts s):rest) _)
                   -> case (f s) of
                        Just (a, s') -> Just (a, st { k = ((KI_Stmts s'):rest)})
                        Nothing -> Nothing
                 _ -> Nothing

liftAExp :: RewriteM AExp a -> RewriteM State a
liftAExp (RewriteM f) =
    RewriteM $ \st -> case st of
                 (State ((KI_AExp s):rest) _) ->
                   case (f s) of
                     Just (a, s') -> Just (a, st { k = ((KI_AExp s'):rest) })
                     Nothing -> Nothing
                 _ -> Nothing

liftBExp :: RewriteM BExp a -> RewriteM State a
liftBExp (RewriteM f) =
    RewriteM $ \st -> case st of
                 (State ((KI_BExp s):rest) _) ->
                   case (f s) of
                     Just (a, s') -> Just (a, st { k = ((KI_BExp s'):rest) })
                     Nothing -> Nothing
                 _ -> Nothing

-- Pulls out the store from the State, keeping the state unchanged.
getStore :: RewriteM State Store
getStore = RewriteM $ \state@(State _k store) -> Just $ (store, state)

setStore :: Store -> RewriteM State ()
setStore store' = RewriteM $ \state -> Just $ ((), state { store = store' })

getK :: RewriteM State K
getK = liftK get

setK :: K -> RewriteM State ()
setK = liftK . set

matchStmt :: RewriteM State Stmts
matchStmt = RewriteM $ \state ->
    case state of
        (State ((KI_Stmts stmt):_) _) -> Just (stmt, state)
        _                             -> Nothing

---------------------------------------------------------------------
-- Semantics
-- If this is expanded in other files, it may lose the inlining
-- unless 'imp' is marked INLINE.
eval_imp :: Pgm -> State
eval_imp pgm = evalOnePath imp $ impInitState pgm


----------------------------------------------------------------------
-- Rules

imp :: [Rewrite State]
imp =   [ liftK     assignHeat
        , liftK     assignCool
        ,           assign
        ,           lookupVar
        , liftK     seqStmt
        , liftStmts while
        , liftK     ifHeat
        , liftK     ifCool
        , liftStmts ifT
        , liftStmts ifF
        , liftK     notHeat
        , liftK     notCool
        , liftBExp  notBExp
        , liftK     leHeatL
        , liftK     leCoolL
        , liftK     leHeatR
        , liftK     leCoolR
        , liftBExp  le
        , liftK     addHeatL
        , liftK     addCoolL
        , liftK     addHeatR
        , liftK     addCoolR
        , liftAExp  add
        , liftK     divHeatL
        , liftK     divCoolL
        , liftK     divHeatR
        , liftK     divCoolR
        , liftAExp  div
        , liftAExp  negate
        , liftStmts block
        , liftK     emptyBlock
        ]

seqStmt :: Rewrite K
seqStmt = do k <- get
             case k of
                ((KI_Stmts (StPair s1 s2)):rest)
                    -> set $ (KI_Stmts s1):(KI_Stmts $ s2):rest
                _   -> matchFail

assign :: Rewrite State
assign = do k <- getK
            store <- getStore
            case k of
                ((KI_Stmts (id := Int i)):rest)
                  -> do setK rest
                        setStore (insert id i store)
                _ -> matchFail

assignHeat :: Rewrite K
assignHeat =
    do  k <- get
        case k of
            ((KI_Stmts (_ := Int _)):_) -> matchFail
            ((KI_Stmts (id := aexp)):rest)
              -> set $ (KI_AExp aexp):(KI_Stmts (id := AHole)):rest
            _ -> matchFail

assignCool :: Rewrite K
assignCool =
    do  k <- get
        case k of
            ((KI_AExp (Int i)):(KI_Stmts (id := AHole)):rest)
              -> set $ (KI_Stmts (id := (Int i))):rest
            _ -> matchFail

while :: Rewrite Stmts
while = do stmts <- get
           case stmts of
                (While cond body)
                  -> set $ (If cond
                           (StmtsBlock $ StPair (Block body)
                                                (While cond body))
                           EmptyBlock)
                _ -> matchFail

ifT :: Rewrite Stmts
ifT = do stmts <- get
         case stmts of
              (If (Bool True) stmtsTrue _) -> set (Block stmtsTrue)
              _ -> matchFail

ifF :: Rewrite Stmts
ifF = do stmts <- get
         case stmts of
            (If (Bool False) _ stmtsFalse) -> set (Block stmtsFalse)
            _ -> matchFail

ifHeat :: Rewrite K
ifHeat = do k <- get
            case k of
              ((KI_Stmts (If (Bool _) _ _)):_) -> matchFail
              ((KI_Stmts (If cond stmtsTrue stmtsFalse)):rest)
                -> set $ (KI_BExp cond):
                            (KI_Stmts (If BHole stmtsTrue stmtsFalse)):rest
              _ -> matchFail

ifCool :: Rewrite K
ifCool = do k <- get
            case k of
              ((KI_BExp (Bool b)):
                (KI_Stmts (If BHole stmtsTrue stmtsFalse)):rest)
                -> set $ (KI_Stmts (If (Bool b) stmtsTrue stmtsFalse)):rest
              _ -> matchFail

notHeat :: Rewrite K
notHeat = do k <- get
             case k of ((KI_BExp (Not (Bool _))):_) -> matchFail
                       ((KI_BExp (Not bexp)):rest)
                         -> set $ (KI_BExp bexp):(KI_BExp (Not BHole)):rest
                       _ -> matchFail

notCool :: Rewrite K
notCool = do k <- get
             case k of
                ((KI_BExp (Bool b)):(KI_BExp (Not BHole)):rest)
                    -> set $ (KI_BExp (Not (Bool b))):rest
                _   -> matchFail

notBExp :: Rewrite BExp
notBExp = do exp <- get
             case exp of
                 (Not (Bool b)) -> set (Bool (not b))
                 _ -> matchFail

leHeatL :: Rewrite K
leHeatL = do k <- get
             case k of
                ((KI_BExp (Int _ :<= _)):_) -> matchFail
                ((KI_BExp (lhs :<= rhs)):rest)
                   -> set $ (KI_AExp lhs):(KI_BExp (AHole :<= rhs)):rest
                _ -> matchFail

leCoolL :: Rewrite K
leCoolL = do k <- get
             case k of
                ((KI_AExp (Int i)):(KI_BExp (AHole :<= rhs)):rest)
                  -> set $ (KI_BExp (Int i :<= rhs)):rest
                _ -> matchFail

leHeatR :: Rewrite K
leHeatR = do k <- get
             case k of
                ((KI_BExp (Int _ :<= Int _)):_) -> matchFail
                ((KI_BExp (lhs :<= rhs)):rest)
                      -> set $ (KI_AExp rhs):(KI_BExp (lhs :<= AHole)):rest
                _ -> matchFail

leCoolR :: Rewrite K
leCoolR = do k <- get
             case k of
               ((KI_AExp (Int i)):(KI_BExp (lhs :<= AHole)):rest)
                 -> set $ (KI_BExp (lhs :<= Int i)):rest
               _ -> matchFail

le :: Rewrite BExp
le = do exp <- get
        case exp of
          (Int i :<= Int j) -> set $ (Bool (i <= j))
          _ -> matchFail

addHeatL :: Rewrite K
addHeatL = do k <- get
              case k of
                 ((KI_AExp (Int _ :+ _)):_) -> matchFail
                 ((KI_AExp (lhs :+ rhs)):rest)
                    -> set $ (KI_AExp lhs):(KI_AExp (AHole :+ rhs)):rest
                 _ -> matchFail

addCoolL :: Rewrite K
addCoolL = do k <- get
              case k of
                 ((KI_AExp (Int i)):(KI_AExp (AHole :+ rhs)):rest)
                   -> set $ (KI_AExp (Int i :+ rhs)):rest
                 _ -> matchFail

addHeatR :: Rewrite K
addHeatR = do k <- get
              case k of
                 ((KI_AExp (Int _ :+ Int _)):_) -> matchFail
                 ((KI_AExp (lhs :+ rhs)):rest)
                       -> set $ (KI_AExp rhs):(KI_AExp (lhs :+ AHole)):rest
                 _ -> matchFail

addCoolR :: Rewrite K
addCoolR = do k <- get
              case k of
                ((KI_AExp (Int i)):(KI_AExp (lhs :+ AHole)):rest)
                  -> set $ (KI_AExp (lhs :+ Int i)):rest
                _ -> matchFail

add :: Rewrite AExp
add = do exp <- get
         case exp of
           (Int i :+ Int j) -> set $ (Int $ i + j)
           _ -> matchFail

divHeatL :: Rewrite K
divHeatL = do k <- get
              case k of
                 ((KI_AExp (Int _ :/ _)):_) -> matchFail
                 ((KI_AExp (lhs :/ rhs)):rest)
                    -> set $ (KI_AExp lhs):(KI_AExp (AHole :/ rhs)):rest
                 _ -> matchFail

divCoolL :: Rewrite K
divCoolL = do k <- get
              case k of
                 ((KI_AExp (Int i)):(KI_AExp (AHole :/ rhs)):rest)
                   -> set $ (KI_AExp (Int i :/ rhs)):rest
                 _ -> matchFail

divHeatR :: Rewrite K
divHeatR = do k <- get
              case k of
                 ((KI_AExp (Int _ :/ Int _)):_) -> matchFail
                 ((KI_AExp (lhs :/ rhs)):rest)
                       -> set $ (KI_AExp rhs):(KI_AExp (lhs :/ AHole)):rest
                 _ -> matchFail

divCoolR :: Rewrite K
divCoolR = do k <- get
              case k of
                ((KI_AExp (Int i)):(KI_AExp (lhs :/ AHole)):rest)
                  -> set $ (KI_AExp (lhs :/ Int i)):rest
                _ -> matchFail

div :: Rewrite AExp
div = do exp <- get
         case exp of
           (Int i :/ Int j) | j /= 0
             -> set $ (Int $ i `Prelude.div` j)
           _ -> matchFail

negate :: Rewrite AExp
negate = do exp <- get
            case exp of
              (Negate i) ->  set $ Int (-1 * i)
              _ -> matchFail

lookupVar :: Rewrite State
lookupVar = do k <- getK
               store <- getStore
               case k of
                 ((KI_AExp (Var x)):rest) | member x store
                    -> let exp = KI_AExp $ Int $ findWithDefault undefined x store in
                       set $ State (exp:rest) store
                 _  -> matchFail

block :: Rewrite Stmts
block = do stmts <- get
           case stmts of
             (Block (StmtsBlock s)) -> set s
             _ -> matchFail

emptyBlock :: Rewrite K
emptyBlock = do stmts <- get
                case stmts of
                  ((KI_Stmts (Block EmptyBlock)):rest) -> set rest
                  _ -> matchFail

----------------------------------------------------------------------
--  Sample programs to test syntax and semantics.
--
--  ./Test  -m KTutImp -e 'mapM print $ map eval_imp […]'
--      (where … = sum_imp, divide_imp, div0_imp)
--  (Eventually Test will be able find all of the `x :: Pgm` here
--  and evaluate them all for you.)

sum_imp :: Integer -> Pgm                           --  'sum.imp'
sum_imp n = Pgm ids stmts  where
    ids   = ["n", "sum"]                            --  int n, sum
    stmts = mkStmts                                 --
          [ "n" := Int n                            --  n = $n
          , "sum" := Int 0                          --  sum = 0
          , While (Not (Var "n" :<= (Int 0)))       --  while (!(n <= 0)) {
               (StmtsBlock (mkStmts                 --
                 [ "sum" := (Var "sum" :+ Var "n")  --    sum = sum + n
                 , "n" := (Var "n" :+ Negate 1)     --    n = n + -1
                 ]))                                --  }
          ]

divide_imp :: Pgm
divide_imp = Pgm ids stmts  where
    ids   = ["a", "b", "r"]                         --  int a, b, r
    stmts = mkStmts                                 --
          [ "a" := Int 100                          --  a = 100
          , "b" := Int 3                            --  b = 3
          , "r" := (Var "a" :/ Var "b")             --  r = a / b
          ]

div0_imp :: Pgm
div0_imp = Pgm ids stmts  where
    ids   = ["r"]
    stmts = mkStmts [ "r" := (Int 42 :/ Int 0) ]
