{-  Abstract syntax and semantics for the K tutorial 'Imp' language.

    (This would normally be in a separate repo that uses this library,
    but it's here while we do development on the framework.)

    This is a translation to KMonad of the K syntax and semantics for the
    Imp programming language and associated examples from the K
    Tutorial[1]. There is a separate implementation of Imp in the
    imp-semantics repo[2] which is not the same.

    [1]: https://github.com/runtimeverification/pl-tutorial/blob/master/1_k/2_imp/lesson_5/imp.md
    [2]: https://github.com/runtimeverification/imp-semantics
-}

{-# OPTIONS_GHC -Wno-unused-top-binds #-}
module NImp () where

import Data.Map (Map, findWithDefault, fromList, insert, member)

{----------------------------------------------------------------------
    Abstract Syntax

    This is almost exactly parallel (including the textual ordering and
    format) to 'module IMP-SYNTAX' in K except that, since it directly
    builds an AST, we leave out things such as parens that are relevant
    only to parsing text to an AST and strictness annotations that are
    actually part of the semantics. (We do however, for convenience,
    keep the precedence settings, both to document them and because it's
    handy when building an AST in Haskell code.)

    Below we refer to the semantics as written in K as 'KTutImp'.
-}

type Id     = String            -- In K, supplied by DOMAINS-SYNTAX.

data AExp   = Int Integer
            | Var Id
            | Negate Integer    -- Cannot negate AExps for some reason.
            | AExp :/ AExp
         -- | Parens AExp       -- Needed for concrete syntax only.
            | AExp :+ AExp
            -- "Heating" rewrite rules generate a "hole" as a placeholder
            -- for an extracted expression that we are reducing. Once fully
            -- evaluated, a "cooling" rule will plug that normal form back
            -- into the hole. (In K, these are automatically generated by
            -- the strict/seqstrict attributes.)
            | AHole

data BExp   = Bool Bool
            | AExp :<= AExp
            | Not BExp
         -- | Parens BExp       -- Needed for concrete syntax only.
            | BExp :&& BExp
            | BHole             -- As per AHole above.

data Stmt   = Block [Stmt]
            | Id := AExp
            | If BExp Stmt Stmt
            | While BExp Stmt
data Pgm    = Pgm Ids Stmt
type Ids    = [Id]

                                -- Same precedence values as the prelude.
infixl 7  :/
infix  6  :+                    -- KTutImp: Left-assoc for more efficient parsing.
infix  4  :<=
infixl 3  :&&                   -- Should be RA! But broken this way in KTutImp.

--  Make all this showable just for convenience and debugging.
deriving instance Show AExp
deriving instance Show BExp
deriving instance Show Stmt
deriving instance Show Pgm

----------------------------------------------------------------------
-- Semantics

-- Generic parts
type Rewrite a = a -> Maybe a
type Semantics a = [Rewrite a]

-- Evaluate a program using Imp semantics (genercise this to all Semantics).
eval_imp :: Pgm -> State
eval_imp pgm = eval imp $ impInitState pgm

----------------------------------------
-- User provided Language definition

data State = State { k :: K, store :: Store }  deriving Show
impInitState :: Pgm -> State
impInitState (Pgm ids pgm) = State [KI_Stmt pgm] (impInitStore ids)

type Store = Map Id Integer
impInitStore :: [Id] -> Store
impInitStore ids = fromList $ zip ids (repeat 0)

type K = [KItem]
data KItem = KI_Stmt Stmt
           | KI_AExp AExp
           | KI_BExp BExp
           deriving Show

imp :: Semantics State
imp =   [ liftK     assignHeat
        , liftK     assignCool
        ,           assign
        ,           lookupVar
        , liftK     seqStmt
        , liftStmt  while
        , liftK     ifHeat
        , liftK     ifCool
        , liftStmt  ifT
        , liftStmt  ifF
        , liftK     notHeat
        , liftK     notCool
        , liftBExp  notBExp
        , liftK     leHeatL
        , liftK     leCoolL
        , liftK     leHeatR
        , liftK     leCoolR
        , liftBExp  le
        , liftK     addHeatL
        , liftK     addCoolL
        , liftK     addHeatR
        , liftK     addCoolR
        , liftAExp  add
        , liftK     divHeatL
        , liftK     divCoolL
        , liftK     divHeatR
        , liftK     divCoolR
        , liftAExp  div
        , liftAExp  negate
        ]
    where
        seqStmt :: Rewrite K
        seqStmt ((KI_Stmt (Block (s:ss))):rest)
              = Just $ (KI_Stmt s):(KI_Stmt $ Block ss):rest
        seqStmt _ = Nothing

        assign :: Rewrite State
        assign (State ((KI_Stmt (id := Int i)):rest) store)
             = Just $ State rest (insert id i store)
        assign _ = Nothing

        assignHeat :: Rewrite K
        assignHeat ((KI_Stmt (_ := Int _)):_) = Nothing
        assignHeat ((KI_Stmt (id := aexp)):rest)
               = Just $ (KI_AExp aexp):(KI_Stmt (id := AHole)):rest
        assignHeat _ = Nothing

        assignCool :: Rewrite K
        assignCool ((KI_AExp (Int i)):(KI_Stmt (id := AHole)):rest)
               = Just $ (KI_Stmt (id := (Int i))):rest
        assignCool _ = Nothing


        while :: Rewrite Stmt
        while (While cond body)
            = Just $ (If cond  (Block [body, (While cond body)])
                               (Block []))
        while _ = Nothing

        ifT :: Rewrite Stmt
        ifT (If (Bool True) stmtTrue _) = Just $ stmtTrue
        ifT _ = Nothing

        ifF :: Rewrite Stmt
        ifF (If (Bool False) _ stmtFalse) = Just $ stmtFalse
        ifF _ = Nothing

        ifHeat :: Rewrite K
        ifHeat ((KI_Stmt (If (Bool _) _ _)):_) = Nothing
        ifHeat ((KI_Stmt (If cond stmtTrue stmtFalse)):rest)
             = Just $ (KI_BExp cond):stmt:rest
             where stmt = (KI_Stmt (If BHole stmtTrue stmtFalse))
        ifHeat _ = Nothing

        ifCool :: Rewrite K
        ifCool ((KI_BExp (Bool b)):(KI_Stmt (If BHole stmtTrue stmtFalse)):rest)
               = Just $ ((KI_Stmt (If (Bool b) stmtTrue stmtFalse)):rest)
        ifCool _ = Nothing

        notHeat :: Rewrite K
        notHeat ((KI_BExp (Not (Bool _))):_) = Nothing
        notHeat ((KI_BExp (Not bexp)):rest)
               = Just $ (KI_BExp bexp):(KI_BExp (Not BHole)):rest
        notHeat _ = Nothing

        notCool :: Rewrite K
        notCool ((KI_BExp (Bool b)):(KI_BExp (Not BHole)):rest)
               = Just $ ((KI_BExp (Not (Bool b))):rest)
        notCool _ = Nothing

        notBExp :: Rewrite BExp
        notBExp (Not (Bool b)) = Just $ (Bool (not b))
        notBExp _ = Nothing

        leHeatL :: Rewrite K
        leHeatL ((KI_BExp (Int _ :<= _)):_) = Nothing
        leHeatL ((KI_BExp (lhs :<= rhs)):rest)
              = Just $ (KI_AExp lhs):(KI_BExp (AHole :<= rhs)):rest
        leHeatL _ = Nothing

        leCoolL :: Rewrite K
        leCoolL ((KI_AExp (Int i)):(KI_BExp (AHole :<= rhs)):rest)
              = Just $ (KI_BExp (Int i :<= rhs)):rest
        leCoolL _ = Nothing

        leHeatR :: Rewrite K
        leHeatR ((KI_BExp (Int _ :<= Int _)):_) = Nothing
        leHeatR ((KI_BExp (lhs :<= rhs)):rest)
              = Just $ (KI_AExp rhs):(KI_BExp (lhs :<= AHole)):rest
        leHeatR _ = Nothing

        leCoolR :: Rewrite K
        leCoolR ((KI_AExp (Int i)):(KI_BExp (lhs :<= AHole)):rest)
              = Just $ (KI_BExp (lhs :<= Int i)):rest
        leCoolR _ = Nothing

        le :: Rewrite BExp
        le (Int i :<= Int j) = Just $ (Bool (i <= j))
        le _ = Nothing

        addHeatL :: Rewrite K
        addHeatL ((KI_AExp (Int _ :+ _)):_) = Nothing
        addHeatL ((KI_AExp (lhs :+ rhs)):rest)
               = Just $ (KI_AExp lhs):(KI_AExp (AHole :+ rhs)):rest
        addHeatL _ = Nothing

        addCoolL :: Rewrite K
        addCoolL ((KI_AExp (Int i)):(KI_AExp (AHole :+ rhs)):rest)
               = Just $ (KI_AExp (Int i :+ rhs)):rest
        addCoolL _ = Nothing

        addHeatR :: Rewrite K
        addHeatR ((KI_AExp (Int _ :+ Int _)):_) = Nothing
        addHeatR ((KI_AExp (Int lhs :+ rhs)):rest)
               = Just $ (KI_AExp rhs):(KI_AExp (Int lhs :+ AHole)):rest
        addHeatR _ = Nothing

        addCoolR :: Rewrite K
        addCoolR ((KI_AExp (Int i)):(KI_AExp (Int lhs :+ AHole)):rest)
               = Just $ (KI_AExp (Int lhs :+ Int i)):rest
        addCoolR _ = Nothing

        add :: Rewrite AExp
        add (Int i :+ Int j) = Just $ (Int (i + j))
        add _ = Nothing

        negate :: Rewrite AExp
        negate (Negate i) = Just $ (Int (-1 * i))
        negate _ = Nothing

        divHeatL :: Rewrite K
        divHeatL ((KI_AExp (Int _ :/ _)):_) = Nothing
        divHeatL ((KI_AExp (lhs :/ rhs)):rest)
               = Just $ (KI_AExp lhs):(KI_AExp (AHole :/ rhs)):rest
        divHeatL _ = Nothing

        divCoolL :: Rewrite K
        divCoolL ((KI_AExp (Int i)):(KI_AExp (AHole :/ rhs)):rest)
               = Just $ (KI_AExp (Int i :/ rhs)):rest
        divCoolL _ = Nothing

        divHeatR :: Rewrite K
        divHeatR ((KI_AExp (Int _ :/ Int _)):_) = Nothing
        divHeatR ((KI_AExp (Int lhs :/ rhs)):rest)
               = Just $ (KI_AExp rhs):(KI_AExp (Int lhs :/ AHole)):rest
        divHeatR _ = Nothing

        divCoolR :: Rewrite K
        divCoolR ((KI_AExp (Int i)):(KI_AExp (Int lhs :/ AHole)):rest)
               = Just $ (KI_AExp (Int lhs :/ Int i)):rest
        divCoolR _ = Nothing

        div :: Rewrite AExp
        div (Int i :/ Int j) | j /= 0 = Just $ (Int (i `Prelude.div` j))
        div _ = Nothing

        lookupVar :: Rewrite State
        lookupVar (State ((KI_AExp (Var x)):rest) store)
                  | member x store
                = Just $ State (exp:rest) store
                where exp = KI_AExp $ Int $ findWithDefault undefined x store
        lookupVar _ = Nothing

--  XXX KMonad should generate this.
liftK :: Rewrite K -> Rewrite State
liftK f state =
    case f (k state) of
           Just k' -> Just $ state { k = k' }
           Nothing -> Nothing

liftStmt :: Rewrite Stmt -> Rewrite State
liftStmt f state =
    case state of (State ((KI_Stmt s):rest) _) ->
                    case f s of
                        Just s' -> Just $ state { k = ((KI_Stmt s'):rest) }
                        Nothing -> Nothing
                  _ -> Nothing

liftBExp :: Rewrite BExp -> Rewrite State
liftBExp f state =
    case state of (State ((KI_BExp s):rest) _) ->
                    case f s of
                        Just s' -> Just $ state { k = ((KI_BExp s'):rest) }
                        Nothing -> Nothing
                  _ -> Nothing

liftAExp :: Rewrite AExp -> Rewrite State
liftAExp f state =
    case state of (State ((KI_AExp s):rest) _) ->
                    case f s of
                        Just s' -> Just $ state { k = ((KI_AExp s'):rest) }
                        Nothing -> Nothing
                  _ -> Nothing

----------------------------------------------------------------------
--  Sample programs to test syntax and semantics.
--
--  ./Test  -m KImp -e 'mapM print $ map eval_imp […]'
--      (where … = sum_imp, divide_imp, div0_imp)
--  (Eventually Test will be able find all of the `x :: Pgm` here
--  and evaluate them all for you.)

sum_imp :: Pgm                                      --  'sum.imp'
sum_imp = Pgm ids stmt  where
    ids   = ["n", "sum"]                            --  int n, sum
    stmt = Block
         [ "n" := Int 100                           --  n = 100
         , "sum" := Int 0                           --  sum = 0
         , While (Not (Var "n" :<= (Int 0))) (Block --  while (!(n <= 0)) {
                [ "sum" := (Var "sum" :+ Var "n")   --    sum = sum + n
                , "n" := (Var "n" :+ Negate 1)      --    n = n + -1
                ])                                  --  }
         ]

divide_imp :: Pgm
divide_imp = Pgm ids stmt  where
    ids   = ["a", "b", "r"]                         --  int a, b, r
    stmt = Block
         [ "a" := Int 100                           --  a = 100
         , "b" := Int 3                             --  b = 3
         , "r" := (Var "a" :/ Var "b")              --  r = a / b
         ]

div0_imp :: Pgm
div0_imp = Pgm ids stmt  where
    ids   = ["r"]
    stmt  = Block [ "r" := (Int 42 :/ Int 0) ]

----------------------------------------------------------------------
-- Library Functions (Not part of KImp)

eval :: Semantics a -> a -> a
eval rewrites state = eval' rewrites where
    eval' []     = state
    eval' (r:rs) = case (r state) of
                        Nothing     -> eval' rs
                        Just state' -> eval rewrites state'
